### ISSUE TITLE
Is there a way not to have the bushes on the edge of the lawn?

### ISSUE THREAD

**Issue by TrollBlox** [HenryJk/PvZWidescreen#10]

**Comment by HenryJk** [comment]
Replace images/B*.png with blank image

**Comment by TrollBlox** [comment]
I don't see those files in my local copy, only in the source code. How would I do that for my local copy?

**Comment by HenryJk** [comment]
you have to unpack the main.pak first, use pvztoolkit or other tools to unpack it

**Comment by TrollBlox** [comment]
Thank you I figured it out. it sucks that there's that ugly dirt patch there lol. oh well. Thanks
