### ISSUE TITLE
No save files upon installing the patch + language

### ISSUE THREAD

**Issue by Cianez** [HenryJk/PvZWidescreen#2]
Hi.

Is there a way to use our save files with this patch? I believe that they're stored in main.pak but I'm not sure (can't open it either).
Also this patch seems to work only with the english localization of the game. Maybe you can find a way to make it work for the other languages too.

**Comment by HenryJk** [comment]
Save file is not in main.pak file, it should be in C:\ProgramData\PopCap Games\Plants Vs. Zombies. Language other than English is beyond the scope of this mod, but you can try replacing lawnstrings.txt and hope for the best.

**Comment by Cianez** [comment]
Yeah I just noticed, though for some reason it's not loading any of my profiles, everything is blank like if I've just installed the game on a new machine (and the saves are still there where you pointed out). Is it normal?

I'll try replacing lawnstrings.txt with the one of another language then, thank you.
