### ISSUE TITLE
Game doesn't look no where near as good as the provided pictures

### ISSUE THREAD

**Issue by RealZyther** [HenryJk/PvZWidescreen#20]
Pretty self-explanatory, this is what I mean
![GameSelector](https://user-images.githubusercontent.com/86556103/202308396-74b82fd1-3ea1-4789-bfc7-7d5c1e8283fb.png)
The game is meant to look like this picture (https://github.com/HenryJk/PvZWidescreen/blob/main/screenshots/GameSelector.png)
When I load into the game, it looks like this picture
![PlantsVsZombies_gGD5lrgB3t](https://user-images.githubusercontent.com/86556103/202308528-73baafff-dd80-4fb9-b050-4cc5baee0250.jpg)
Much worse (At least I think so?)
How do I fix this?

**Comment by HenryJk** [comment]
You have to finish the game for the trophies and accessories to appear.

**Comment by RealZyther** [comment]
? That's not what I'm talking about... I said the quality of the game lmao..

**Comment by HenryJk** [comment]
The screenshot is in windowed mode, if you use fullscreen, it will be blurrier

**Comment by RealZyther** [comment]
Ah, I thought this mod not only got rid of black borders but also increased quality (when I saw the screenshots) my mistake, thanks for letting me know.
