### ISSUE TITLE
Assets don't load properly

### ISSUE THREAD

**Issue by AppleHair** [HenryJk/PvZWidescreen#3]
Hi!
I saw your mod on youtube and thought it looked very nice. 
I've gone ahead and downloaded the mod, dragged the files into the PvZ folder, opened pvz_widescreen, and it didn't look anything like the video I saw on youtube. everything was messed up and it just looked horrible.

![Screenshot 2022-03-16 232912 PNG](https://user-images.githubusercontent.com/95587502/158788033-38fae119-64c9-4f33-971f-a930230be263.jpg)

then when I got into the adventure mode, there were even more problems.

The zombies weren't visible at the start:
![Screenshot 2022-03-16 233032](https://user-images.githubusercontent.com/95587502/158788580-042e9936-cc6b-495f-8421-e9b140cbb62a.jpg)

a lot of assets of in-game stuff weren't rendered from a certain distance:

![Screenshot 2022-03-16 233049](https://user-images.githubusercontent.com/95587502/158789047-8a118553-7c3a-45c2-9bcb-81d8968c131e.jpg)

![Screenshot 2022-03-16 233156](https://user-images.githubusercontent.com/95587502/158789059-995bf66e-01e9-4939-8cc3-a0e23f4ad18f.jpg)

am I doing something wrong? what can I do to fix this?

**Comment by AsyrafFile** [comment]
Are you using original (containing Micheal Jackson) or GOTY version?

**Comment by BalancedLight** [comment]
is hardware acceleration on? this occurred with me when i turned it off.

**Comment by AppleHair** [comment]
> Are you using original (containing Micheal Jackson) or GOTY version?

I'm using the GOTY version. Is this a Problem? Do I need to use another version?

**Comment by AppleHair** [comment]
> is hardware acceleration on? this occurred with me when i turned it off.

OK, THAT FIXED IT. THANK YOU 😊

**Comment by AsyrafFile** [comment]
> > Are you using original (containing Micheal Jackson) or GOTY version?
> 
> I'm using the GOTY version. Is this a Problem? Do I need to use another version?

No. Just fine because I afraid Original version may not supported.

**Comment by AsyrafFile** [comment]
I am suggesting reopen this issue and rename it, because this is actual bug.

**Comment by HenryJk** [comment]
So, it's technically a bug, since hardware acceleration shouldn't be needed for this mod. However, it's something I haven't find a fix yet.
