### ISSUE TITLE
[Feature Request] Add high quality assets from Xbox 360 release.

### ISSUE THREAD

**Issue by Patrxgt** [HenryJk/PvZWidescreen#4]
It would be cool to have Xbox 360 assets in the PC version of the game with more art around playable area, which console version had.

**Comment by HenryJk** [comment]
XBOX version has the same pixel density, it won't make the image sharper on windowed mode, and will make playable area smaller in fullscreen mode. Besides, many files I already took from console version anyway.

**Comment by Patrxgt** [comment]
Then it would be nice, if you could at least give an option to choose between PC and Xbox 360 style, where Xbox 360 mode would use menu and maps with smaller playable arena from this version. I know it's probably not the goal of this mod, but it would make PC version feel complete and the best from any other version.

**Comment by HenryJk** [comment]
That's too hard to do, I suggest you look at other mod for that.

**Comment by Patrxgt** [comment]
Okay, thanks for answer. One more thing, are you using assets from the mobile versions or you've made widescreen versions of original arts by hand?

**Comment by HenryJk** [comment]
Mostly from console, but modified a bit to fit the pc version better.

**Comment by Patrxgt** [comment]
Ok, thanks for answer.
PS. Are you going to bring MJ zombie back to the game in your mod? I've tried other mods, but those aren't compatible with yours.
